language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO_VERSION=1.8.17
  - DJANGO_VERSION=1.9.12
  - DJANGO_VERSION=1.10.4
install:
  - pip install django==$DJANGO_VERSION
  - pip install -e .
script:
  - python manage.py test unslashed
