language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.7.1
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO_VERSION=1.7
    - python: "2.6"
      env: DJANGO_VERSION=1.7.1
install:
  - pip install django==$DJANGO_VERSION
  - pip install -e .
script:
  - python manage.py test unslashed